#pragma once

#define MASTER_LEFT

#define SERIAL_PIO_USE_PIO1
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP8
#define SERIAL_USART_RX_PIN GP9

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define BOOTMAGIC_ROW_RIGHT 8
#define BOOTMAGIC_COLUMN_RIGHT 6
